name: Daily Commit

on:
  schedule:
    # Runs at 21:10 UTC (9:10 PM UTC)
    - cron: '10 21 * * *'

jobs:
  create-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure we have full git history
          fetch-depth: 0

      - name: Setup Git config for 24f1002064@ds.study.iitm.ac.in
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "24f1002064@ds.study.iitm.ac.in"

      - name: Create and commit daily update
        run: |
          # Create or update a file with current timestamp
          echo "Last updated: $(date -u)" > update.txt
          
          # Stage the changes
          git add update.txt
          
          # Create commit
          git commit -m "Daily automated update $(date -u)"
          
          # Push using the built-in GITHUB_TOKEN
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.TT }}
